"""ChunkRepository — hybrid_search_rrf + bulk upsert via asyncpg (LLD §5, §4.2)."""

from __future__ import annotations

from uuid import UUID

from app.models import EmbeddedChunk, ScoredChunk
from app.repositories.base import AsyncpgRepository


class ChunkRepository(AsyncpgRepository):
    async def delete_for_document(self, document_id: UUID) -> int:
        """Remove all chunks for a document so re-ingestion is idempotent
        (prevents duplicate / mixed-embedding-space rows on re-embed)."""
        async with self.pool.acquire() as conn:
            result = await conn.execute(
                "DELETE FROM chunk_embeddings WHERE document_id = $1",
                document_id,
            )
        # asyncpg returns e.g. "DELETE 18"
        try:
            return int(result.split()[-1])
        except (ValueError, IndexError):
            return 0

    async def bulk_upsert(self, chunks: list[EmbeddedChunk]) -> int:
        """Batch insert into chunk_embeddings. tsv is generated by a column trigger / default."""
        if not chunks:
            return 0
        import json
        rows = [
            (
                c.document_id,
                c.pipeline_id,
                c.organization_id,
                c.chunk_index,
                c.token_count,
                c.content,
                str(c.embedding),
                c.page_number,
                c.strategy.value,
                c.source_type,
                c.media_path,
                json.dumps(c.metadata),
            )
            for c in chunks
        ]
        async with self.pool.acquire() as conn:
            await conn.executemany(
                """
                INSERT INTO chunk_embeddings
                    (document_id, pipeline_id, organization_id, chunk_index,
                     token_count, content, embedding, page_number, chunk_strategy,
                     source_type, media_path, metadata)
                VALUES ($1,$2,$3,$4,$5,$6,$7::vector,$8,$9,$10,$11,$12::jsonb)
                """,
                rows,
            )
        return len(rows)

    async def hybrid_search(
        self,
        query_text: str,
        query_emb: list[float],
        pipeline_id: UUID,
        limit: int = 20,
        metadata_filter: dict | None = None,
    ) -> list[ScoredChunk]:
        import json
        filter_json = json.dumps(metadata_filter) if metadata_filter else None
        rows = await self.pool.fetch(
            "SELECT * FROM hybrid_search_rrf($1, $2::vector, $3, $4, 60, $5)",
            query_text,
            str(query_emb),
            pipeline_id,
            limit,
            filter_json,
        )
        return [
            ScoredChunk(
                chunk_id=r["chunk_id"],
                content=r["content"],
                rrf_score=float(r["rrf_score"]),
            )
            for r in rows
        ]

    async def get_by_filename(self, pipeline_id: UUID, filename: str) -> list[ScoredChunk]:
        """Fetch all chunks belonging to a document with the matching filename in a pipeline."""
        rows = await self.pool.fetch(
            """
            SELECT ce.id, ce.content
            FROM chunk_embeddings ce
            JOIN documents d ON d.id = ce.document_id
            WHERE ce.pipeline_id = $1 AND d.filename = $2
            ORDER BY ce.chunk_index ASC
            """,
            pipeline_id,
            filename,
        )
        return [
            ScoredChunk(
                chunk_id=r["id"],
                content=r["content"],
                rrf_score=0.5,
            )
            for r in rows
        ]

    async def attach_metadata(self, chunks: list[ScoredChunk]) -> None:
        """Join document + chunk fields for citation popovers."""
        if not chunks:
            return
        ids = [c.chunk_id for c in chunks]
        rows = await self.pool.fetch(
            """
            SELECT ce.id, ce.document_id, ce.page_number, ce.chunk_index, d.filename, ce.source_type, ce.media_path
            FROM chunk_embeddings ce
            JOIN documents d ON d.id = ce.document_id
            WHERE ce.id = ANY($1::uuid[])
            """,
            ids,
        )
        by_id = {r["id"]: r for r in rows}
        for c in chunks:
            meta = by_id.get(c.chunk_id)
            if not meta:
                continue
            c.document_id = meta["document_id"]
            c.page_number = meta["page_number"]
            c.chunk_index = meta["chunk_index"]
            c.filename = meta["filename"]
            c.source_type = meta["source_type"]
            c.media_path = meta["media_path"]

    async def sample_for_pipeline(self, pipeline_id: UUID, limit: int = 10) -> list[dict]:
        rows = await self.pool.fetch(
            """
            SELECT id, content, chunk_index
            FROM chunk_embeddings
            WHERE pipeline_id = $1
            ORDER BY RANDOM()
            LIMIT $2
            """,
            pipeline_id,
            limit,
        )
        return [dict(r) for r in rows]

    async def count_for_pipeline(self, pipeline_id: UUID) -> int:
        val = await self.pool.fetchval(
            "SELECT COUNT(*) FROM chunk_embeddings WHERE pipeline_id = $1",
            pipeline_id,
        )
        return int(val or 0)
